### ISSUE TITLE
Rule 3 Outdated

### ISSUE THREAD

**Issue by bcpurleigh** [danharper/portsdegree#5]
Hello! Firstly, thanks for making this useful tool, it's been a great help throughout my final year at Portsmouth to keep track of what I need to aim for! However I have been informed that the classification formulae for rule 3 have been modified again. 

The previous rule, prior to September 2017 for rule 3 was:
```
the minimum classification in which 50% of the combined relevant credits
at Level 5 and Level 6 were attained after first discounting the marks in the worst 20
credits both at Level 5 and at Level 6.
```

Whereas the new changes to the rule are as highlighted below

```
the minimum classification in which **more than** 50% of the combined relevant credits
at Level 5 and Level 6 were attained after first discounting the marks in the worst 20
credits both at Level 5 and at Level 6.
```

This was identified by a senior lecturer at Portsmouth. I have a fix lined up to be made into a PR shortly to save you fixing this yourself. The guidebook that is linked from the current repo via `index.html` is still correct and seems to update itself. 

Best regards,

Ben

**Comment by danharper** [comment]
Thanks for fixing! #6

**Comment by jacovanc** [comment]
I see this fix has now been reverted. Was there another change I'm unaware of? As far as I'm aware it should still be *more than* 50% of the combined relevant credits.
